"""initial_schema

Revision ID: 411179a33dfa
Revises: bee6da152a66
Create Date: 2026-03-28 19:33:28.091238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '411179a33dfa'
down_revision: Union[str, None] = 'bee6da152a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_name'), 'batches', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('unit_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_operations_batch_id'), 'unit_operations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_unit_operations_equipment_id'), 'unit_operations', ['equipment_id'], unique=False)
    op.create_table('unit_operation_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_unitop_id', sa.Integer(), nullable=False),
    sa.Column('to_unitop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_unitop_id'], ['unit_operations.id'], ),
    sa.ForeignKeyConstraint(['to_unitop_id'], ['unit_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_operation_dependencies_from_unitop_id'), 'unit_operation_dependencies', ['from_unitop_id'], unique=False)
    op.create_index(op.f('ix_unit_operation_dependencies_to_unitop_id'), 'unit_operation_dependencies', ['to_unitop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_operation_dependencies_to_unitop_id'), table_name='unit_operation_dependencies')
    op.drop_index(op.f('ix_unit_operation_dependencies_from_unitop_id'), table_name='unit_operation_dependencies')
    op.drop_table('unit_operation_dependencies')
    op.drop_index(op.f('ix_unit_operations_equipment_id'), table_name='unit_operations')
    op.drop_index(op.f('ix_unit_operations_batch_id'), table_name='unit_operations')
    op.drop_table('unit_operations')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_batches_name'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###