"""add_batch_dates

Revision ID: d22df80a4a60
Revises: 411179a33dfa
Create Date: 2026-03-28 20:43:07.389807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd22df80a4a60'
down_revision: Union[str, None] = '411179a33dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('start', sa.DateTime(), nullable=False))
    op.add_column('batches', sa.Column('end', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'end')
    op.drop_column('batches', 'start')
    # ### end Alembic commands ###